# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dfd5b6ac19a18235f824c047e2ce156649c62bb6b8b68d1a617746f6ccb35e97f58f4ec888033b49d29ddd980c94ddc4ee2faab908f4be8de6a235ba6e527267

test:
  secret_key_base: c67191ed0522a6a3ec8e4c2cb04f3e706d7ceeacd889072de853b15d973e9e6d988df27d9b950bea257aa64bdc1d7825d0601691e98532051165a480f1281d17

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
